<script src="/js/organisation.js"></script>
<script>
    viewModel.v.name('<tpl if="name">{name}</tpl>')
    viewModel.v.fullname('<tpl if="fullname">{fullname}</tpl>')
    viewModel.v.headers('<tpl if="headers">{headers}</tpl>')
    viewModel.v.founders('<tpl if="founders">{founders}</tpl>')
    viewModel.v.inn('<tpl if="inn">{inn}</tpl>')
    viewModel.v.kpp('<tpl if="kpp">{kpp}</tpl>')
    viewModel.v.ogrn('<tpl if="ogrn">{ogrn}</tpl>')
    viewModel.v.legal_address('<tpl if="legal_address">{legal_address}</tpl>')
    viewModel.v.fact_address('<tpl if="fact_address">{fact_address}</tpl>')
    viewModel.v.www('<tpl if="www">{www}</tpl>')
    viewModel.v.contact_person('<tpl if="contact_person">{contact_person}</tpl>')
    viewModel.v.headers_phones('<tpl if="headers_phones">{headers_phones}</tpl>')
    viewModel.v.phone('<tpl if="phone">{phone}</tpl>')
    viewModel.v.email('<tpl if="email">{email}</tpl>')
    viewModel.v.sro('<tpl if="sro">{sro}</tpl>')
    viewModel.v.info('<tpl if="info">{info}</tpl>')
</script>
