<script src="/js/ko.validate.js"></script>
<script src="/js/bid.js?_dc=1"></script>
<script>
viewModel.tenderId = '{_id}'
viewModel.tenderLeftTime = 0;
viewModel.start_price = parseFloat('{start_price}')
viewModel.step_price = parseFloat('{step_price}');
viewModel.v.date_start(decodeURIComponent('{bid.date_start}'))
viewModel.v.date_fin(decodeURIComponent('{bid.date_fin}'))
viewModel.v.price_pos(decodeURIComponent('{bid.price_pos}'))
viewModel.v.price_full(decodeURIComponent('{bid.price_full}'))
viewModel.v.conditions_advance(decodeURIComponent('{bid.conditions_advance}'))
viewModel.v.max_contract_val(decodeURIComponent('{bid.max_contract_val}'))
viewModel.v.notes(decodeURIComponent('{bid.notes}'))
viewModel.v.file_descript(decodeURIComponent('{bid.file_descript}'))
</script>
<script src="/js/auction.js?_dc=1"></script>